// <auto-generated />
using System;
using Blog.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Blog.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Blog.Models.Data.Articles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Slug");

                    b.Property<int>("Sorting");

                    b.Property<DateTime>("Timepost");

                    b.Property<string>("Title");

                    b.Property<string>("Urlimg");

                    b.HasKey("Id");

                    b.ToTable("article");
                });

            modelBuilder.Entity("Blog.Models.Data.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArticlesId");

                    b.Property<string>("Comment")
                        .IsRequired();

                    b.Property<string>("Mail")
                        .IsRequired();

                    b.Property<DateTime>("Timecomment");

                    b.HasKey("Id");

                    b.HasIndex("ArticlesId");

                    b.ToTable("comment");
                });

            modelBuilder.Entity("Blog.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Pass");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Blog.Models.Data.Comments", b =>
                {
                    b.HasOne("Blog.Models.Data.Articles", "Articles")
                        .WithMany("coms")
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
